// SPDX-License-Identifier: AGPL-3.0-only
//! Cross-language differential test: the Rust `residual_channel` port vs the Python reference
//! (`weltwerk/verify/residual_channel.py`). This is GATEWAY_SPEC.md §8 step 1 — the gating-risk validation
//! that the Rust audit reproduces the Python decisions.
//!
//! The fixtures in `tests/fixtures/` were generated by `gen_fixtures.py` running the PYTHON `audit` on the
//! planted null/channel generators; each carries Python's MI, CMI and DECISION. This test:
//!   1. recomputes MI and CMI with the Rust estimators on the SAME samples and asserts VALUE-parity (1e-9) —
//!      these estimators are RNG-free, so they must equal Python to float precision (this also guards fixture
//!      integrity: a mis-copied digit changes the counts and breaks parity);
//!   2. runs the full Rust `audit` and asserts DECISION-parity with Python.
//!
//! `decisions match, floats need not`: the shuffle-null moments are NOT compared — Rust uses a per-stratum LCG,
//! not CPython's Mersenne-Twister, so the null distribution differs at the float level while the decision is
//! invariant (the planted cases sit far from threshold).

use ursprung::{audit_default, conditional_mutual_information, mutual_information, Sample};

struct Fixture {
    decision_token: String,
    mi: f64,
    cmi: f64,
    samples: Vec<Sample>,
}

fn parse(text: &str) -> Fixture {
    let mut decision_token = String::new();
    let mut mi = f64::NAN;
    let mut cmi = f64::NAN;
    let mut samples: Vec<Sample> = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        if let Some(rest) = line.strip_prefix('#') {
            for tok in rest.split_whitespace() {
                if let Some(v) = tok.strip_prefix("decision=") {
                    decision_token = v.to_string();
                } else if let Some(v) = tok.strip_prefix("mi=") {
                    mi = v.parse().expect("mi parse");
                } else if let Some(v) = tok.strip_prefix("cmi=") {
                    cmi = v.parse().expect("cmi parse");
                }
            }
        } else {
            let b = line.as_bytes();
            let mut i = 0;
            while i + 3 <= b.len() {
                let x = (b[i] - b'0') as i64;
                let y = (b[i + 1] - b'0') as i64;
                let z = (b[i + 2] - b'0') as i64;
                samples.push((x, y, z.to_string())); // Sample = (i64, i64, String)
                i += 3;
            }
        }
    }
    Fixture { decision_token, mi, cmi, samples }
}

const NULL_FIXTURE: &str = include_str!("fixtures/null.tsv");
const CHANNEL_FIXTURE: &str = include_str!("fixtures/channel.tsv");

fn assert_value_parity(f: &Fixture) {
    assert_eq!(f.samples.len(), 800, "fixture must hold 800 samples");
    let xy: Vec<(i64, i64)> = f.samples.iter().map(|s| (s.0, s.1)).collect();
    let mi = mutual_information(&xy);
    let cmi = conditional_mutual_information(&f.samples);
    assert!((mi - f.mi).abs() < 1e-9, "MI parity: rust={mi} python={}", f.mi);
    assert!((cmi - f.cmi).abs() < 1e-9, "CMI parity: rust={cmi} python={}", f.cmi);
}

#[test]
fn null_value_parity() {
    assert_value_parity(&parse(NULL_FIXTURE));
}

#[test]
fn channel_value_parity() {
    assert_value_parity(&parse(CHANNEL_FIXTURE));
}

#[test]
fn null_decision_parity() {
    let f = parse(NULL_FIXTURE);
    let r = audit_default(&f.samples);
    assert_eq!(r.decision.as_str(), f.decision_token, "null decision must match Python");
    assert_eq!(r.decision.as_str(), "CONSISTENT_WITH_NULL");
}

#[test]
fn channel_decision_parity() {
    let f = parse(CHANNEL_FIXTURE);
    let r = audit_default(&f.samples);
    assert_eq!(r.decision.as_str(), f.decision_token, "channel decision must match Python");
    assert_eq!(r.decision.as_str(), "RESIDUAL_DEPENDENCE");
}
